CREATE TABLE benchmarks (
    ID INT auto_increment NOT NULL,
    backType VARCHAR(10) NOT NULL,
    execTime BIGINT NOT NULL,
    callDate DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(ID)
);